// Build: scan src/plugins for plugin folders, generate the plugin list, bundle a single userscript file.
// Usage: bun run build.ts            (full build)
//        bun run build.ts --gen-only (only regenerate src/generated/plugins.ts)

import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const VERSION_NUMBER = '2.2.0';
const DATE = '20261010';
const VERSION = `[${DATE}] v${VERSION_NUMBER}`;
const OUT_DIR = 'userscript';
const OUT_FILE = join(OUT_DIR, '[Youtube] Video Memory.user.js');
const META_FILE = join(OUT_DIR, '[Youtube] Video Memory.meta.js');
const HOMEPAGE = 'https://github.com/0-V-linuxdo/Youtube-Memory';

const header = `// ==UserScript==
// @name         [Youtube] Video Memory [${DATE}] v${VERSION_NUMBER}
// @namespace    0_V userscripts/Youtube Save & Resume Progress
// @version      ${VERSION}
// @description  Save & resume YouTube playback progress reliably (waits for the player, skips ads, per-video sessions), timestamp-link choice dialog, records/storage/transcript settings, void++-style plugins, 💾 badge toggle and optional Google Drive sync.
// @update-log   ${VERSION} · Clean-room rewrite: new progress engine (no lost progress), &t= choice dialog, void++-style plugin architecture and settings UI, 💾 badge toggle plugin, per-video Google Drive sync, page scrollbar kept while the dialog is open.
// @author       0_V
// @license      MIT
// @match        *://*.youtube.com/*
// @icon         ${HOMEPAGE}/raw/refs/heads/main/main_icon/main_icon.svg
// @homepageURL  ${HOMEPAGE}
// @supportURL   ${HOMEPAGE}/issues
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_listValues
// @grant        GM_xmlhttpRequest
// @connect      oauth2.googleapis.com
// @connect      www.googleapis.com
// ==/UserScript==
`;

const credits = `
/*
 * Based on "Youtube Save/Resume Progress" by Costin Alexandru Sandu
 * (https://greasyfork.org/scripts/487305, v1.5.1). Thank you!
 *
 * Generated file — edit the TypeScript sources under src/ and run \`bun run build\`.
 * 本文件由 src/ 下的 TypeScript 源码经 \`bun run build\` 生成，请勿直接修改。
 * YouTube enforces Trusted Types: never assign innerHTML / outerHTML; build the UI with DOM APIs.
 * YouTube 启用了 Trusted Types：禁止给 innerHTML / outerHTML 赋值，只能用 DOM API 构建界面。
 */
`;

/* ------------------------------------------------------------------ plugin list */

function pluginDirs(base: string): string[] {
  if (!existsSync(base)) return [];
  return readdirSync(base)
    .filter(name => !name.startsWith('_') && !name.startsWith('.'))
    .filter(name => statSync(join(base, name)).isDirectory() && existsSync(join(base, name, 'index.ts')))
    .sort();
}

function generatePluginList(): void {
  const core = pluginDirs('src/plugins/_core').map(name => ({ id: `core_${name}`, path: `../plugins/_core/${name}` }));
  const optional = pluginDirs('src/plugins').map(name => ({ id: `plugin_${name}`, path: `../plugins/${name}` }));
  const all = [...core, ...optional];
  const lines = [
    '// AUTO-GENERATED by build.ts from the folders in src/plugins — do not edit.',
    "import type { PluginDef } from '../api/plugins';",
    ...all.map(p => `import ${p.id} from '${p.path}';`),
    '',
    `export const plugins: PluginDef[] = [${all.map(p => p.id).join(', ')}];`,
    ''
  ];
  mkdirSync('src/generated', { recursive: true });
  writeFileSync('src/generated/plugins.ts', lines.join('\n'));
  console.log(`plugins: ${all.map(p => p.path.replace('../plugins/', '')).join(', ')}`);
}

generatePluginList();
if (process.argv.includes('--gen-only')) process.exit(0);

/* ------------------------------------------------------------------ bundle */

const result = await Bun.build({
  entrypoints: ['src/index.ts'],
  target: 'browser',
  format: 'iife',
  minify: false,
  sourcemap: 'none',
  define: { __VERSION__: JSON.stringify(VERSION) },
  plugins: [{
    name: 'css-as-text',
    setup(build) {
      build.onLoad({ filter: /\.css$/ }, args => ({
        contents: `export default ${JSON.stringify(readFileSync(args.path, 'utf8'))};`,
        loader: 'js'
      }));
    }
  }]
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const code = await result.outputs[0].text();
const output = `${header}${credits}\n'use strict';\n${code}`;

// N-0.4: Trusted Types — the bundle must never assign innerHTML / outerHTML.
const forbidden = /\b(?:inner|outer)HTML\s*=(?!=)/;
if (forbidden.test(output)) {
  const line = output.split('\n').findIndex(l => forbidden.test(l)) + 1;
  console.error(`Build failed: innerHTML/outerHTML assignment found in the output (line ${line}).`);
  process.exit(1);
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, output);
writeFileSync(META_FILE, header);
console.log(`built ${OUT_FILE} (${(output.length / 1024).toFixed(1)} KiB), ${VERSION}`);
